[package]
name = "ctb-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = { version = "0.3.13", default-features = false }
osu-types = { path = "../osu-rs/osu-types" }
osu-parser = { path = "../osu-rs/osu-parser" }
kira = { version = "0.5.3", default-features = false, features = ['wav'] }
#kira = { git = "https://github.com/tesselode/kira", rev = "842a08f" }
#kira-cpal = { git = "https://github.com/tesselode/kira", rev = "842a08f" }
#kira-loaders = { git = "https://github.com/tesselode/kira", rev = "842a08f" }